### ISSUE TITLE
How to train the model?

### ISSUE THREAD

**Issue by Changhy1115** [zcajiayin/L2D#2]
Hi!
I read your paper and the code in the last days, and now I have a question about the code. In the project, I find **test_learned.py** and **validation.py** which is used to test and validate, and the network is loaded directly in the file. So I want to ask you how to train the model? @zcajiayin

**Comment by Changhy1115** [comment]
Sorry, I've found the training process in the **PPO_jssp_multiInstances.py**.

**Comment by zcajiayin** [comment]
That's right. Sorry for misleading title of the file. Should've been `main.py` or something.
